config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  devise_for 	:users, 
				:path => '', 
  				:path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  				:controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  								:registrations => 'registrations' }

  resources :users, only: [ :show ]

  resources :rooms
  resources :photos

  resources :rooms do
  	resources :reservations, only: [ :create ]
    resources :reviews, only: [ :create, :destroy ]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  
  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  post '/notify' => 'reservations#notify'
  post '/your_trips' => 'reservations#your_trips'

  get '/search' => 'pages#search'

end

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">AirAlien</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li><a href="#">Link</a></li>
        <li><%= link_to "Rooms", rooms_path %></li>
        <li>
          <%= link_to conversations_path do %>
            <i class="fa fa-envelope-o"></i> Messages
          <% end %>
        </li>
      </ul>

      <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "Where are you going?", class: "form-control" %>
        </div>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>

        <% else %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">  
              <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %> &nbsp;
              <%= current_user.fullname %> 
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>

              <li><%= link_to "Your Listing", rooms_path %> </li>
              <li><%= link_to "Your Reservations", your_reservations_path %> </li>
              <li><%= link_to "Your Trips", your_trips_path %> </li>

              <li role="separator" class="divider"></li>              
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { confirm: "Sure to sign out?"} %></li>
            </ul>
          </li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { confirm: "Sure to sign out?"} %></li>

        <% end %>



      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>